export interface State {
  runtimeOverride: any;
  runtimeOverrideBase: any;
  runtimeOverrideLabel: string | null;
  diagnosticsRuntimeConfig: any;
  diagnosticsRuntimePresetId: string | null;
  diagnosticsSelections: Record<string, any>;
  lastDiagnosticsSuite: string | null;
  lastDiffusionRequest: any;
  lastEnergyRequest: any;
  lastReport: any;
  lastReportInfo: any;
  lastMetrics: any;
  lastInferenceStats: any;
  lastMemoryStats: any;
  activePipeline: any;
  activePipelineModelId: string | null;
  activeModelId: string | null;
  registeredModelIds: string[];
  modelTypeCache: Record<string, string>;
  modelAvailability: {
    total: number;
    run: number;
    translate: number;
    embedding: number;
    diffusion: number;
    energy: number;
  };
  modeModelId: {
    run: string | null;
    translate: string | null;
    embedding: string | null;
    diffusion: string | null;
    energy: string | null;
  };
  runAbortController: AbortController | null;
  runGenerating: boolean;
  runPrefilling: boolean;
  runLoading: boolean;
  diffusionGenerating: boolean;
  diffusionLoading: boolean;
  energyGenerating: boolean;
  energyLoading: boolean;
  convertActive: boolean;
  downloadActive: boolean;
  surface: string;
  uiTask: string;
  uiMode: string;
  lastPrimaryMode: string;
  lastTaskMode: Record<string, string>;
  runLog: any[];
  runCounter: number;
  embeddingDemoDocuments: any[];
  storageUsageBytes: number;
  storageQuotaBytes: number;
  storageInspectorScanning: boolean;
  storageInspectorLastScan: number;
  gpuMaxBytes: number;
  systemMemoryBytes: number;
  uiIntervalId: any;
  lastStorageRefresh: number;
  activeDownloadId: string | null;
  quickModelCatalog: any[];
  quickModelCatalogError: string | null;
  quickModelCatalogLoading: boolean;
  quickModelActionModelId: string | null;
  quickModelStorageIds: string[];
  downloadProgress: any;
  energyDemoId: string | null;
  lastEnergyResult: any;
}

export declare const state: State;
