export const state = {
  phase: 'booting',
  bootError: null,
  model: null,
  modelId: null,
  modelStatus: {},
  quickModelCatalog: [],
  downloadProgress: null,
  generating: false,
  prefilling: false,
  abortController: null,
  conversationHistory: [],
  conversationAnnotations: [],
  conversationModelId: null,
  settings: {
    temperature: 0,
    topK: 0,
    topP: 1,
    maxTokens: 256,
    readbackInterval: 0,
    runtimeProfile: 'profiles/default',
  },
  preset: 'fast',
  wordQualityEnabled: true,
  modelBusy: false,
  settingsBusy: false,
  xrayEnabled: true,
  tokenInspectorActive: true,
  lastInspection: null,
  lastInferenceStats: null,
  lastRun: null,
  lastImportedReport: null,
};
