export const state = {
  phase: 'booting',
  bootError: null,
  model: null,
  modelId: null,
  modelStatus: {},
  quickModelCatalog: [],
  downloadProgress: null,
  generating: false,
  prefilling: false,
  abortController: null,
  conversationHistory: [],
  conversationModelId: null,
  settings: {
    temperature: 0,
    topK: 0,
    topP: 1,
    maxTokens: 1024,
    readbackInterval: 0,
    runtimeProfile: 'profiles/default',
  },
  preset: 'fast',
  wordQualityEnabled: false,
  liveTokSec: false,
  xrayEnabled: false,
  lastInspection: null,
  lastInferenceStats: null,
  lastRun: null,
  lastImportedReport: null,
};
