export const ERROR_CODES = {
  CONFIG_PRESET_UNKNOWN: 'DOPPLER_CONFIG_PRESET_UNKNOWN',
  GPU_UNAVAILABLE: 'DOPPLER_GPU_UNAVAILABLE',
  GPU_DEVICE_FAILED: 'DOPPLER_GPU_DEVICE_FAILED',
  LOADER_MANIFEST_INVALID: 'DOPPLER_LOADER_MANIFEST_INVALID',
  LOADER_SHARD_INDEX_INVALID: 'DOPPLER_LOADER_SHARD_INDEX_INVALID',
  DISTRIBUTION_P2P_CONTRACT_UNSUPPORTED: 'DOPPLER_DISTRIBUTION_P2P_CONTRACT_UNSUPPORTED',
  DISTRIBUTION_P2P_TRANSPORT_UNCONFIGURED: 'DOPPLER_DISTRIBUTION_P2P_TRANSPORT_UNCONFIGURED',
  DISTRIBUTION_P2P_TRANSPORT_UNAVAILABLE: 'DOPPLER_DISTRIBUTION_P2P_TRANSPORT_UNAVAILABLE',
  DISTRIBUTION_P2P_TRANSPORT_TIMEOUT: 'DOPPLER_DISTRIBUTION_P2P_TRANSPORT_TIMEOUT',
  DISTRIBUTION_P2P_TRANSPORT_ABORTED: 'DOPPLER_DISTRIBUTION_P2P_TRANSPORT_ABORTED',
  DISTRIBUTION_P2P_TRANSPORT_INTEGRITY_MISMATCH: 'DOPPLER_DISTRIBUTION_P2P_TRANSPORT_INTEGRITY_MISMATCH',
  DISTRIBUTION_P2P_TRANSPORT_POLICY_DENIED: 'DOPPLER_DISTRIBUTION_P2P_TRANSPORT_POLICY_DENIED',
  DISTRIBUTION_P2P_TRANSPORT_INTERNAL: 'DOPPLER_DISTRIBUTION_P2P_TRANSPORT_INTERNAL',
  DISTRIBUTION_P2P_TRANSPORT_PAYLOAD_INVALID: 'DOPPLER_DISTRIBUTION_P2P_TRANSPORT_PAYLOAD_INVALID',
  DISTRIBUTION_SHARD_HASH_MISMATCH: 'DOPPLER_DISTRIBUTION_SHARD_HASH_MISMATCH',
  DISTRIBUTION_SHARD_SIZE_MISMATCH: 'DOPPLER_DISTRIBUTION_SHARD_SIZE_MISMATCH',
  DISTRIBUTION_SHARD_MANIFEST_VERSION_SET_MISMATCH: 'DOPPLER_DISTRIBUTION_SHARD_MANIFEST_VERSION_SET_MISMATCH',
};

export function createDopplerError(code, message) {
  const error = new Error(`[${code}] ${message}`);
  error.code = code;
  return error;
}
