export declare const initialize: any;
export declare const loadModel: any;
export declare const _loadWeights: any;
export declare const _initRoPE: any;
export declare const _initConvLayerStates: any;
export declare const _loadVisionWeights: any;
export declare const _ensureVisionWeightsLoaded: any;
export declare const _loadAudioWeights: any;
export declare const _ensureAudioWeightsLoaded: any;
