import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { spawnSync } from 'node:child_process';

const result = spawnSync(
  process.execPath,
  ['tools/render-readme-evidence-chart.js', '--check'],
  {
    cwd: process.cwd(),
    encoding: 'utf8',
  }
);

assert.equal(
  result.status,
  0,
  `README evidence chart check failed\nstdout:\n${result.stdout}\nstderr:\n${result.stderr}`
);

const svg = await readFile('assets/doppler-webgpu-evidence.svg', 'utf8');
const readme = await readFile('README.md', 'utf8');
const benchmarkRows = svg.match(/class="benchmark-row"/g) ?? [];
const receiptLinks = svg.match(/data-receipt="benchmarks\/vendors\/results\//g) ?? [];

assert.match(svg, /Generated by tools\/render-readme-evidence-chart\.js/);
assert.equal(benchmarkRows.length, 9, 'README evidence chart must contain nine comparable rows');
assert.equal(receiptLinks.length, 9, 'every chart row must bind its source receipt');
assert.match(svg, /RATE DISTRIBUTION \/ FASTER &gt;/);
assert.match(svg, /tok\/s/);
assert.match(svg, /embedding\/s/);
assert.match(svg, /rerank\/s/);
assert.doesNotMatch(svg, /ms\/token|ms\/embedding|ms\/rerank|LOWER IS FASTER/);
assert.match(readme, /higher steady-state inference throughput/);
assert.match(readme, /higher is faster/);
assert.doesNotMatch(readme, /lower decode ms\/token|latency distributions/);

console.log('readme-evidence-chart-contract.test: ok');
